// Assets list can be extended if needed but must be supported by the Frankfurter API
export const FIAT_ASSETS = {
  AUD: "AUD",
  CAD: "CAD",
  CHF: "CHF",
  CNY: "CNY",
  CZK: "CZK",
  DKK: "DKK",
  GBP: "GBP",
  HKD: "HKD",
  HUF: "HUF",
  IDR: "IDR",
  INR: "INR",
  JPY: "JPY",
  KRW: "KRW",
  MXN: "MXN",
  MYR: "MYR",
  NZD: "NZD",
  PLN: "PLN",
  RON: "RON",
  SEK: "SEK",
  SGD: "SGD",
  TRY: "TRY",
  USD: "USD",
};
